# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Guide.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 502)
        Dialog.setStyleSheet("background-color : rgb(240,255,240)")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(175, 20, 450, 60))
        font = QtGui.QFont()
        font.setFamily("에스코어 드림 5 Medium")
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color : #323c3c")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(390, 100, 20, 380))
        self.line.setStyleSheet("color : #323c3c")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("에스코어 드림 5 Medium")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(420, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("에스코어 드림 5 Medium")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 361, 271))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Image/guide.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(420, 135, 141, 35))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Image/guide2.PNG"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(570, 130, 211, 41))
        font = QtGui.QFont()
        font.setFamily("에스코어 드림 6 Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(420, 210, 351, 241))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Image/guide_2.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 120, 211, 31))
        font = QtGui.QFont()
        font.setFamily("에스코어 드림 6 Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "프로그램 사용 가이드"))
        self.label.setText(_translate("Dialog", "프로그램 사용 가이드"))
        self.label_2.setText(_translate("Dialog", "1. 모션으로 제어하기"))
        self.label_3.setText(_translate("Dialog", "2. 태블릿으로 제어하기"))
        self.label_6.setText(_translate("Dialog", "을 선택하면"))
        self.label_8.setText(_translate("Dialog", "아래 제스처를 취하면"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
