# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Loading(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(250, 125)
        Form.setStyleSheet("background-color : rgb(240,255,240)")
        Form.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 40, 151, 41))
        font = QtGui.QFont()
        font.setFamily("에스코어 드림 6 Bold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(170, 25, 71, 71))
        # set qmovie as label
        self.movie = QtGui.QMovie("Image/loading.gif")
        self.label_2.setMovie(self.movie)
        self.label_2.setScaledContents(True)
        self.movie.start()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "로딩 중..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Loading()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
